project_id = "obswcosfipqjvklqlnrj"

[functions.send-password-reset]
verify_jwt = false

[functions.ai-rewrite-chat]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.webhook-proxy]
verify_jwt = true